#!/bin/sh
if [ $PWD = ~/tex ]; then
  perl -i -pe 's/[\200-\377]/sprintf"\\x%x",ord$&/eg' tex.w # avoid "File is not UTF-8" error (comm-utf8.ch) due to printable.ch
fi
if [ $1 = +u ]; then
  u=+u
  shift
fi
file=$1
if [ "$2" = "" ]; then
  ch=/dev/null
else
  ch=${2%.ch}.ch
fi
file=${file%.w}
test -e $file.w || { echo '! Cannot open input file' $file.w; exit 1; }
test -e $ch || { echo '! Cannot open change file' $ch; exit 1; }
~/cweb/ctangle $u -b -h -p "$@" || exit
if [ "$3" ]; then
  out=$3.c
else
  out=${file##*/}.c
fi
if [ "$u" ]; then
  sed -i 's/sig\xD0\xB0ction/sigaction/g' $out
  sed -i 's/st\xD0\xB0t/stat/g' $out
else
  sed -i 's/sigXA1ction/sigaction/g' $out
  sed -i 's/stXA1t/stat/g' $out
fi
perl -i -pe 'if(/const dev_desc/../const conf_desc/){if(/^struct\{/){$v=1}if($v){if(/\*\d+:\*/){$x++}}}if(/const conf_desc/../};/){if(/\*\d+:\*/){$y++}}END{if($x!=$y){print"ERROR: number of sections with declarations is not equal to number of sections with parameters\n";$?=1}}' $out || exit
perl -ne 'if(/^#/||/^$/){next}if(/const dev_desc/../const conf_desc/){if(/^struct\{/){$v=1}if($v){if(/\w+;/){$n++}if(/\*:\d+\*/){$h{++$x}=$n;$n=0}}}if(/const conf_desc/../};/){if($w){$n++}if(/\*\d+:\*/){$y++;$w=1}if(/\*:(\d+)\*/){if($h{$y}!=$n-1){print"ERROR: number of parameters does not match in section $1\n";$e=1}$w=0;$n=0}}END{$?=$e}' $out || exit
sed -i s/SIZEOF_CONF_DESC/$(perl -ne 'if(/const dev_desc/../const conf_desc/){if(/\w+;/){$a+=$&=~/^(w|bcd)/?2:1}}END{print$a}' $out)/ $out
perl -i -pe 'if(/const dev_desc/../const conf_desc/){if(/^struct\{/){$v=1}if($v){if(/\w+;/){$a+=$&=~/^(w|bcd)/?2:1}if(/\*:\d+\*/){$h{++$x}=$a;$a=0}}}if(/const conf_desc/../};/){if(/\*\d+:\*/){$y++}s/SIZEOF_THIS/$h{$y}/}' $out
perl -i -pe 'if(/const dev_desc/../const conf_desc/){if(/(\w+);/){if($a{$1}){s//$1_$a{$1};/}$a{$1}++}}' $out
