#!/bin/sh
if [ $PWD = ~/tex ]; then
  perl -i -pe 's/[\200-\377]/sprintf"\\x%x",ord$&/eg' tex.w # avoid "File is not UTF-8" error (comm-utf8.ch) due to printable.ch
fi
if [ $PWD = ~/tex/web2w ]; then
  sed -i /§/d web2w.ch # avoid "xord[c]!=invalid_code" error (comm-utf8.ch) in printable.ch
fi
if [ $1 = +u ]; then
  u=+u
  shift
fi
file=$1
if [ "$2" = "" ]; then
  ch=/dev/null
else
  ch=${2%.ch}.ch
fi
file=${file%.w}
test -e $file.w || { echo '! Cannot open input file' $file.w; exit 1; }
test -e $ch || { echo '! Cannot open change file' $ch; exit 1; }
~/cweb/ctangle $u -b -h -p "$@" || exit
if [ "$3" ]; then
  out=$3.c
else
  out=${file##*/}.c
fi
if [ "$u" ]; then
  sed -i 's/sig\xD0\xB0ction/sigaction/g' $out
  sed -i 's/st\xD0\xB0t/stat/g' $out
else
  sed -i 's/sigXA1ction/sigaction/g' $out
  sed -i 's/stXA1t/stat/g' $out
fi
