#!/bin/sh
if [ $PWD = ~/tex ]; then
  perl -i -pe 's/[\200-\377]/sprintf"\\x%x",ord$&/eg' tex.w # avoid "File is not UTF-8" error (comm-utf8.ch) due to printable.ch
fi
file=$1
if [ "$2" = "" ]; then
  ch=/dev/null
else
  ch=${2%.ch}.ch
fi
file=${file%.w}
test -e $file.w || { echo '! Cannot open input file' $file.w; exit 1; }
test -e $ch || { echo '! Cannot open change file' $ch; exit 1; }
~/cweb/ctangle -b -h -p "$@" || exit
if [ "$3" ]; then
  out=$3.c
else
  out=${file##*/}.c
fi
sed -i s/sigXA1ction/sigaction/g $out
sed -i s/stXA1t/stat/g $out
# ---------------- reminder -----------------
grep -o 'cfsetspeed\|cfset[io]speed([^,]\+, \?B0)' $out && exit 1 # do not use cfsetspeed - use cfsetospeed or cfsetispeed; do not use B0 - see its effect by printing wValue of set_control_line_state requests when you use B0, and when opening and closing the tty right after using B0
# ---------------- conf_desc ----------------
grep -q 'const conf_desc' $out && ed -s $out <<'EOF'
/const conf_desc/;?struct{?;.s/$/ \/\/ begin conf_desc/
wq
EOF
perl -i -pe 'if(/begin conf_desc/../const conf_desc/){if(/\*\d+:\*/){$x++}}if(/const conf_desc/../};/){if(/\*\d+:\*/){$y++}}END{if($x!=$y){print"ERROR: number of sections with declarations is not equal to number of sections with parameters\n";$?=1}}' $out || exit
perl -ne 'if(/begin conf_desc/../const conf_desc/){if(/\*\d+:\*/){$x++}if(/\w+;/){$h{$x}++}}if(/const conf_desc/../};/){if(/\*:(\d+)\*/){if($h{$z}){print"ERROR: number of params does not match in section $1\n";$e=1}$z=0}$h{$z}--unless/^#/||/^$/;if(/\*\d+:\*/){$y++;$z=$y}}END{$?=$e}' $out || exit
perl -i -pe 'if(/begin conf_desc/../const conf_desc/){if(/\w+;/){$a+=$&=~/^(w|bcd)/?2:1}}s/SIZEOF_CONF_DESC/$a/' $out
perl -i -pe 'if(/begin conf_desc/../const conf_desc/){if(/\*\d+:\*/){$x++}if(/\w+;/){$h{$x}+=$&=~/^(w|bcd)/?2:1}}if(/const conf_desc/../};/){if(/\*\d+:\*/){$y++}s/SIZEOF_THIS/$h{$y}/}' $out
perl -i -pe 'if(/begin conf_desc/../const conf_desc/){if(/\*\d+:\*/){$x++}s/(\w+);/$1_$x;/}' $out
