#!/bin/sh
file=$1
if [ "$2" = "" ]; then
  ch=/dev/null
else
  ch=$2.ch
fi
test -e $file.w || { echo '! Cannot open input file' $file.w; exit 1; }
test -e $ch || { echo '! Cannot open change file' $ch; exit 1; }
ctie -m $file.m $file.w $ch >/dev/null || { rm -f $file.m; exit 1; }
iconv -f UTF-8 -t UCS-2 $file.m $ch >/dev/null 2>&1 || { echo Bad input; rm $file.m; exit 1; }
grep '@s sigaction' $file.m && { echo ERROR: Use cyrillic a; rm $file.m; exit 1; }
grep 'struct sigaction' $file.m && { echo ERROR: Use cyrillic a; rm $file.m; exit 1; }
grep '@s stat' $file.m && { echo ERROR: Use cyrillic a; rm $file.m; exit 1; }
grep 'struct stat' $file.m && { echo ERROR: Use cyrillic a; rm $file.m; exit 1; }
rm $file.m
~/cweb/cweave -b -h -p "$@" || exit 1
LC_ALL=C grep -q '\\|[^[:cntrl:][:print:]]' $file.tex $file.idx $file.scn && { echo ERROR: one-letter identifiers must be ascii-only; exit 1; } # I do not set \matcharcode for cyrillic letters (because I do not have cyrillic math fonts), so cyrillic one-letter identifiers will be typeset in roman font instead of italic
if [ $PWD != ~/cweb ] || [ $file != cweave ]; then
  grep -q '\\&{delete}' $file.tex $file.idx $file.scn && { echo ERROR: Use @s delete normal; exit 1; }
  grep -q '\\&{new}' $file.tex $file.idx $file.scn && { echo ERROR: Use @s new normal; exit 1; }
fi
grep -q '\\&{line}' $file.tex $file.idx $file.scn && { echo ERROR: Use @s line normal; exit 1; }
sed -i 's/sig\xD0\xB0ction/sigaction/g' $file.tex $file.idx $file.scn
sed -i 's/st\xD0\xB0t/stat/g' $file.tex $file.idx $file.scn
iconv -f ASCII $file.tex $file.idx $file.scn >/dev/null 2>&1 || sed -i '1s/$/-ru/;1i %&тех' $file.tex
[ $file = tel ] && sed -i '1s/-ru//;1i %&тех' $file.tex
