#!/bin/sh
file=$1
if [ "$2" = "" ]; then
  ch=/dev/null
else
  ch=$2.ch
fi
test -e $file.w || { echo '! Cannot open input file' $file.w; exit 1; }
test -e $ch || { echo '! Cannot open change file' $ch; exit 1; }
tmp=$file.cweave.$$
ctie -m $tmp $file.w $ch >/dev/null || { rm -f $tmp; exit 1; } # expand @i
grep '@s sigaction' $tmp && { echo ERROR: Use cyrillic a; rm $tmp; exit 1; }
grep 'struct sigaction' $tmp && { echo ERROR: Use cyrillic a; rm $tmp; exit 1; }
grep '@s stat' $tmp && { echo ERROR: Use cyrillic a; rm $tmp; exit 1; }
grep 'struct stat' $tmp && { echo ERROR: Use cyrillic a; rm $tmp; exit 1; }
rm $tmp
~/cweb/cweave -b -h -p "$@" || exit 1
LC_ALL=C grep -lq '\\|[^[:cntrl:][:print:]]' $file.tex $file.idx $file.scn && { echo ERROR: one-letter identifiers must be ascii-only; exit 1; } # I do not set \matcharcode for cyrillic letters (because I do not have cyrillic math fonts), so cyrillic one-letter identifiers will be typeset in roman font instead of italic
grep -q '\\&{delete}' $file.tex $file.idx $file.scn && { echo ERROR: Use @s delete normal; exit 1; }
grep -q '\\&{new}' $file.tex $file.idx $file.scn && { echo ERROR: Use @s new normal; exit 1; }
grep -q '\\&{line}' $file.tex $file.idx $file.scn && { echo ERROR: Use @s line normal; exit 1; }
sed -i 's/sig\xD0\xB0ction/sigaction/g' $file.tex $file.idx $file.scn
sed -i 's/st\xD0\xB0t/stat/g' $file.tex $file.idx $file.scn
iconv -f ascii $file.tex $file.idx $file.scn >/dev/null 2>&1 || sed -i 1s/$/-ru/ $file.tex
[ $file = tel ] && sed -i 1s/-ru// $file.tex
