#!/bin/sh
dvitype -output-level 0 $1 | grep -q 'TFM file can.t be opened\|check sums do not agree' && \
  { echo ERROR: $1.dvi is not up-to-date; exit; }
mode=viewer ~/mytex/dvips $1.dvi && ~/mytex/open $1.ps
