#!/bin/sh
if dvitype -output-level 0 $1 | grep -q 'TFM file can.t be opened\|check sums do not agree'; then
  echo ERROR: the DVI file is not up-to-date
  exit
fi
set ${1%.dvi}
export mode=viewer
hexdump -s15 -n9 -v -e '"%c"' $1.dvi | grep -q METAFONT && mode=localfont
~/mytex/dvips $1.dvi && ~/mytex/open $1.ps
