#!/bin/sh
if ! dvitype -output-level 0 $1 >/tmp/dvitype.$$; then
  echo ERROR: dvitype
  rm /tmp/dvitype.$$
  exit
fi
if grep -q 'TFM file can.t be opened\|check sums do not agree' /tmp/dvitype.$$; then
  echo ERROR: the DVI file is not up-to-date
  rm /tmp/dvitype.$$
  exit
fi
rm /tmp/dvitype.$$
ps_file=/tmp/PRINT.ps
mode=localfont ~/mytex/dvips ${1%.dvi}.dvi $ps_file && ~/mytex/print $ps_file
