#!/bin/sh
unset gf log # this script is called from mf+/mf-, tex+/tex- (metafont is called here, by MakeTeXPK and via missfont.log; it must not write anything to that files)
mkdir /tmp/mf.$$
resolution=$(cd /tmp/mf.$$; ~/mf/plain "\mode=$mode; mode_setup; show pixels_per_inch; end" | sed -n 's/>> //p')
rm -r /tmp/mf.$$
file=$1
~/dvitype/dvitype $file /dev/stdout 0 '' '' $resolution/1 ''|sed -n '/^Postamble starts at byte/,${s/^Font [0-9]\+: //p}'|grep -v '^[A-Za-z]\+[0-9]* ' && exit 1 # do not use fonts with path
eval "$(hexdump -s 15 -n `hexdump -s 14 -n 1 -e '/1 "%d"' $file` -v -e '/1 "%c"' $file | sed 's/.* /p=/;s/x/sp,/;s/[+-][0-9]*/sp x=& y=/')"
export TEXCONFIG=~/dvips
export DVIPSHEADERS=~/dvips
export VFFONTS=/none
export TEXFONTS=~/tex/TeXfonts
export PKFONTS=~/tex/TeXfonts/$mode
~/dvips/dvips -T $p -O $((x-4736287))sp,$((y-4736287))sp -D $resolution -q $file
ret=$?
if [ -e missfont.log ]; then
  sh missfont.log
  rm missfont.log
  exit 1
fi
exit $ret
