#!/bin/sh
unset name # this script is called from mf+/mf-, tex+/tex- (metafont is called here and in dvifont; it must not write anything to that file)
mkdir /tmp/mf.$$
resolution=$(cd /tmp/mf.$$; ~/mf/plain "\mode=$mode; mode_setup; show pixels_per_inch; end" | sed -n 's/>> //p')
rm -r /tmp/mf.$$
file=$1
~/mytex/dvifont/dvifont $file /dev/null '' '' '' $resolution/1 '' || exit
eval "$(hexdump -s 15 -n `hexdump -s 14 -n 1 -e '/1 "%d"' $file` -v -e '/1 "%c"' $file | sed 's/.* /p=/;s/x/sp,/;s/[+-][0-9]*/sp x=& y=/')"
export TEXCONFIG=~/dvips
export DVIPSHEADERS=~/dvips
export VFFONTS=/none
export TEXFONTS=~/tex/TeXfonts
export PKFONTS=~/tex/TeXfonts/$mode
~/dvips/dvips -T $p -O $((x-4736287))sp,$((y-4736287))sp -D $resolution -q $file
ret=$?
if [ -e missfont.log ]; then
  sh missfont.log
  rm missfont.log
  exit 1
fi
exit $ret
