#!/bin/sh
name=$1
dpi=$(echo $2*$3/1000+0.5 | bc -l | cut -d. -f1)
mag=$(echo $3/1000 | bc -l | sed 's/^\./0./' | cut -d. -f1)
mag=$mag+$(echo $3-$mag*1000 | bc -l)/1000
if [ $name = ${name#*/} ]; then
  [ -e $PKFONTS/$name.${dpi}pk ] && exit 0
else
  mv $name.tfm $name.tfm.$$
  if ! mf "\mode=$mode; mag=$mag; batchmode; input $name" >/dev/null; then
    echo ERROR: mf failed for $name `[ $3 = 1000 ] || echo scaled $3`
    mv $name.tfm.$$ $name.tfm
    exit 1
  fi
  if [ `md5sum $name.tfm | head -c32` != `md5sum $name.tfm.$$ | head -c32` ]; then
    echo ERROR: update $name.tfm
    mv $name.tfm.$$ $name.tfm
    exit 1
  fi
  rm $name.tfm.$$
  if ! ~/mytex/gftopk $name.${dpi}gf; then
    echo ERROR: gftopk failed for $name `[ $3 = 1000 ] || echo scaled $3`
    exit 1
  fi
  exit 0
fi
[ $name = trip ] && { echo ERROR: font \'trip\' is reserved; exit 1; }
if [ -L ~/tex/TeXfonts/$name.tfm ]; then
  fullname=~/mf/$name
else
  fullname=$name
fi
mkdir /tmp/mf.$$
cd /tmp/mf.$$
if ! mf "\mode=$mode; mag=$mag; batchmode; input $fullname" >/dev/null; then
  cd /
  rm -r /tmp/mf.$$
  echo ERROR: mf failed for $fullname `[ $3 = 1000 ] || echo scaled $3`
  exit 1
fi
if ! ~/mytex/gftopk $name.${dpi}gf; then
  cd /
  rm -r /tmp/mf.$$
  echo ERROR: gftopk failed for $fullname `[ $3 = 1000 ] || echo scaled $3`
  exit 1
fi
mkdir -p $PKFONTS
mv $name.${dpi}pk $PKFONTS
cd /
rm -r /tmp/mf.$$
