#!/bin/sh
# run 'make' in mytex/ only when 'make' is run without arguments in tex/ or mf/
if [ "$PWD" != ~/tex ] && [ "$PWD" != ~/mf ] || [ $# != 0 ]; then
  exec make "$@"
fi
make || exit
if [ -e ~/tex/initex ] && [ -e ~/mf/virmf ]; then
  cd ~/mytex
  make
fi
