#!/bin/sh
export edit=/tmp/edit.$$
export gf=/tmp/gf.$$
export tfm=/tmp/tfm.$$
export screen_size=$(screen-size)
~/mf/plain "$@"
ret=$?
~/tex/newline
[ -e $edit ] && em `cat $edit`
if [ $ret = 0 ]; then
  if [ -e $gf ] && [ -e $tfm ]; then
    ~/mytex/gftopk `cat $gf`
  fi
fi
rm -f $edit $gf $tfm
