#!/bin/sh
export edit=/tmp/edit.$$
export gf=/tmp/gf.$$
~/mf/plain "$@"
ret=$?
~/mytex/newline
[ -e $edit ] && ~/mytex/edit
if [ $ret = 0 ]; then
  if [ -e $gf ]; then
    gf_file=`cat $gf`
    if ~/mytex/gftodvi $gf_file; then
      dvi_file=${gf_file%.*}.dvi
      mode=localfont ~/mytex/dvips $dvi_file && ~/mytex/open ${dvi_file%dvi}ps
    fi
  fi
fi
rm -f $edit $gf
