#!/bin/sh
export edit=/tmp/edit.$$
export name=/tmp/name.$$
~/mf/plain "$@"
ret=$?
~/tex/newline
[ -e $edit ] && em `cat $edit`
if [ $ret = 0 ]; then
  gf_file=`grep -s gf$ $name`
  if [ "$gf_file" ]; then
    if ~/mytex/gftodvi $gf_file; then
      dvi_file=${gf_file%.*}.dvi
      mode=localfont ~/mytex/dvips $dvi_file && ~/mytex/print ${dvi_file%dvi}ps
    fi
  fi
fi
rm -f $edit
rm -f $name
