#!/bin/sh
export base=plain
export edit=/tmp/edit.$$
export gf=/tmp/gf.$$
~/mf/virmf "$@"
ret=$?
if [ -t 0 ] && [ -t 1 ]; then
  stty -icanon -echo
  tput u7
  gawk -v RS=R '{print;exit}' | sed -n '/.*;1$/!e echo'
  stty icanon echo
fi
[ -e $edit ] && em `cat $edit`
if [ $ret = 0 ] && [ -e $gf ]; then
  gf_file=`cat $gf`
  if [ "$1" ] && sed -n 1p "$1.mf" "$1" 2>/dev/null | grep -q '^%&'; then
    eval `sed -n '1s/^%!//p' "$1.mf" "$1" 2>/dev/null`
    export pdfpagewidth pdfpageheight pdfhorigin pdfvorigin
  fi
  if ~/mytex/gftodvi $gf_file; then
    dvi_file=${gf_file%.*}.dvi
    ps_file=/tmp/PRINT.ps
    mode=localfont ~/mytex/dvips $dvi_file $ps_file && ~/mytex/print $ps_file
  fi
fi
rm -f $edit $gf
