#!/bin/sh
pkill -x gv
PATH=~/mytex/bin:$PATH
gv $1 2>/dev/null &

# To obtain geometry for ~/.gv, set red desktop backround, run gv, stretch borders to sides,
# create screenshot of active window (enable «without borders» option), save it to x.png and
# see size via «file x.png» and put it as GV.geometry: to ~/.gv and run «tex- 'story \end'»
# and decrease each value one by one separately until red stripe appears
