#!/bin/sh
export edit=/tmp/edit.$$
~/tex/plain "$@"
if [ -t 0 ] && [ -t 1 ]; then
  stty -icanon -echo
  tput u7
  gawk -v RS=R '{print;exit}' | sed -n '/.*;1$/!e echo'
  stty icanon echo
fi
[ -e $edit ] && em `cat $edit`
rm -f $edit
