#!/bin/sh
export edit=/tmp/edit.$$
export dvi=/tmp/dvi.$$
~/tex/plain "$@"
ret=$?
stty -icanon -echo
tput u7
awk -v RS=R '{ print $1; exit }' | sed -n '/.*;1$/!e echo'
stty icanon echo
[ -e $edit ] && env `sed 's/.* /file=&line=/' $edit` ~/em/em
if [ $ret = 0 ]; then
  if [ -e $dvi ]; then
    dvi_file=`cat $dvi`
    mode=screen ~/mytex/dvips $dvi_file && ~/mytex/open ${dvi_file%dvi}ps
  fi
fi
rm -f $edit $dvi
