#!/bin/sh
export edit=/tmp/edit.$$
export dvi=/tmp/dvi.$$
~/tex/plain "$@"
ret=$?
if [ -t 0 ] && [ -t 1 ]; then
  stty -icanon -echo
  tput u7
  gawk -v RS=R '{print;exit}' | sed -n '/.*;1$/!e echo'
  stty icanon echo
fi
[ -e $edit ] && em `cat $edit`
if [ $ret = 0 ]; then
  if [ -e $dvi ]; then
    dvi_file=`cat $dvi`
    mode=screen ~/mytex/dvips $dvi_file && ~/mytex/open ${dvi_file%dvi}ps
  fi
fi
rm -f $edit $dvi
