#!/bin/sh
export format=plain
export edit=/tmp/edit.$$
export dvi=/tmp/dvi.$$
if [ "$1" ] && sed -n 1p "$1.tex" "$1" 2>/dev/null | grep -q '^%&'; then
  format=`sed -n '1s/^%&//p' "$1.tex" "$1" 2>/dev/null`
fi
~/tex/virtex "$@"
ret=$?
if [ -t 0 ] && [ -t 1 ]; then
  stty -icanon -echo
  tput u7
  gawk -v RS=R '{print;exit}' | sed -n '/.*;1$/!e echo'
  stty icanon echo
fi
[ -e $edit ] && em `cat $edit`
if [ $ret = 0 ] && [ -e $dvi ]; then
  dvi_file=`cat $dvi`
  mode=localfont ~/mytex/dvips $dvi_file && ~/mytex/print ${dvi_file%dvi}ps
fi
rm -f $edit $dvi
