#!/bin/sh
export edit=/tmp/edit.$$
~/tex/тех "$@"
ret=$?
if [ -t 0 ] && [ -t 1 ]; then
  stty -icanon -echo
  tput u7
  awk -v RS=R '{ print $1; exit }' | sed -n '/.*;1$/!e echo'
  stty icanon echo
fi
[ -e $edit ] && env `sed 's/.* /file=&line=/' $edit` ~/em/em
rm -f $edit
