#!/bin/sh
export edit=/tmp/edit.$$
export dvi=/tmp/dvi.$$
~/tex/тех "$@"
ret=$?
~/tex/newline
[ -e $edit ] && eval db=/dev/null `sed 's/.* /file=&line=/' $edit` ~/em/em
if [ $ret = 0 ]; then
  if [ -e $dvi ]; then
    dvi_file=`cat $dvi`
    mode=screen ~/mytex/dvips $dvi_file && ~/mytex/open ${dvi_file%dvi}ps
  fi
fi
rm -f $edit $dvi
