#!/bin/sh
export edit=/tmp/edit.$$
export dvi=/tmp/dvi.$$
~/tex/тех "$@"
ret=$?
~/tex/newline
[ -e $edit ] && em `cat $edit`
if [ $ret = 0 ]; then
  if [ -e $dvi ]; then
    dvi_file=`cat $dvi`
    mode=localfont ~/mytex/dvips $dvi_file && ~/mytex/print ${dvi_file%dvi}ps
  fi
fi
rm -f $edit $dvi
